applications:
  app:
    type: python:3.12

    # Define your writeable directory using Upsun rules
    mounts:
      "db":
        source: storage
        source_path: db

    web:
      commands:
        start: gunicorn ll_project.wsgi:application --bind 0.0.0.0:$PORT

    hooks:
      deploy: |
        mkdir -p db
        touch db/db.sqlite3
        python manage.py migrate --noinput
