# Top-level block containing your app container settings
applications:
  learning_log:
    type: "python:3.12"

    hooks:
      build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic --noinput

    web:
      # Change from socket_family to generic HTTP port handling
      commands:
        start: gunicorn -b 0.0.0.0:$PORT learning_log.wsgi:application

# Top-level block mapping web requests to your learning_log app
routes:
  "https://{default}/":
    type: upstream
    upstream: "learning_log:http"
